const currentMonth = date => { const now = new Date(); const value = new Date(`${date}T12:00:00`); return value.getMonth() === now.getMonth() && value.getFullYear() === now.getFullYear(); };
export const totalExpenses = transactions => transactions.filter(t => t.type === 'expense').reduce((sum, t) => sum + Number(t.amount), 0);
export const totalIncome = transactions => transactions.filter(t => t.type === 'income').reduce((sum, t) => sum + Number(t.amount), 0);
export const monthlyTransactions = transactions => transactions.filter(t => currentMonth(t.date));
export const categorySpending = transactions => Object.entries(transactions.filter(t => t.type === 'expense').reduce((all, t) => ({ ...all, [t.category]: (all[t.category] || 0) + Number(t.amount) }), {})).map(([name, amount]) => ({ name, amount })).sort((a,b) => b.amount-a.amount);
export const budgetSummary = (transactions, amount) => { const month = monthlyTransactions(transactions); const withdrawals = month.filter(t => t.source === 'goal_withdrawal').reduce((sum, t) => sum + Number(t.amount), 0); const spent = totalExpenses(month) - withdrawals; const budget = Number(amount || 0); const days = new Date().getDate(); const remainingDays = new Date(new Date().getFullYear(), new Date().getMonth()+1, 0).getDate() - days; const percentage = budget ? Math.round((spent / budget) * 100) : 0; return { budget, spent, remaining: budget - spent, percentage, averageDaily: spent / days, safeDaily: remainingDays > 0 ? Math.max(0, budget-spent) / remainingDays : 0 }; };
export const spendingTrend = transactions => { const days = []; for(let i=6;i>=0;i--) { const d=new Date(); d.setDate(d.getDate()-i); const key=d.toISOString().slice(0,10); days.push({ label:d.toLocaleDateString('en-IN',{weekday:'short'}), amount: totalExpenses(transactions.filter(t=>t.date===key)) }); } return days; };
export const alertsFor = (transactions, budget) => { const summary = budgetSummary(transactions, budget); const categories = categorySpending(monthlyTransactions(transactions)); const alerts=[]; if(summary.budget) { if(summary.percentage > 100) alerts.push({ level:'danger', text:`Your monthly budget has been exceeded by ₹${Math.round(-summary.remaining).toLocaleString('en-IN')}.` }); else if(summary.percentage >= 90) alerts.push({ level:'warning', text:`You've used ${summary.percentage}% of your monthly budget.` }); else if(summary.percentage >= 75) alerts.push({ level:'warning', text:`You've used ${summary.percentage}% of your monthly budget.` }); if(summary.averageDaily > summary.safeDaily && summary.remaining > 0) alerts.push({ level:'warning', text:'At your current spending rate, you may exceed your monthly budget.' }); } if(categories[0]) alerts.push({ level:'info', text:`${categories[0].name} is currently your highest spending category.` }); return alerts; };
export const goalProgress = goal => Math.min(100, Math.round((Number(goal.current_amount) / Number(goal.target_amount)) * 100));
